# Generated by Django 4.0.2 on 2022-03-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploads',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
