# Generated by Django 4.0.2 on 2022-03-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x7f950482ebf0>', max_length=100),
        ),
    ]
