# Generated by Django 4.0.2 on 2022-03-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_uploads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploads',
            new_name='img',
        ),
    ]
