# Generated by Django 4.0.2 on 2022-03-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_uploads_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='No-Image.jpg', upload_to='images/'),
        ),
    ]
