# Generated by Django 4.0.2 on 2022-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='No name Provided', max_length=255),
        ),
    ]
