import Head from "next/head";
import Header from "../components/Header";
import AfterHeader from "../components/AfterHeader";
import Layout from "../components/Layout";
import { Props } from "../typings/types";
import Link from "next/link";

const Home = ({ posts }: Props) => {
  return (
    <Layout>
      <div className="min-w-2xl max-w-7xl mx-auto">
        <Head>
          <title>Mediumize</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <AfterHeader />
          {/* Posts */}
          {posts.map((post) => (
            <Link key={post.slug} href={`${post.img as any as string}`}>
              <div className="flex justify-between p-5 bg-white">
                <img
                  src={post.img ?? post.img}
                  width={100}
                  height={100}
                  alt="Image Post"
                />
                <div className="flex justify-between p-5 bg-white">
                  <div>
                    {post.title} | {post.content} | {post.author_name}
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </main>
      </div>
    </Layout>
  );
};

export const getServerSideProps = async () => {
  const res = await fetch(`http://127.0.0.1:8000/posts/`);
  const posts = await res.json();
  if (!posts) {
    return {
      notFound: true,
    };
  }
  return { props: { posts } };
};

export default Home;
