import Head from "next/head";
import Header from "../components/Header";
import AfterHeader from "../components/AfterHeader";
import Layout from "../components/Layout";
import { Props } from "../typings/types";
import Link from "next/link";

const Home = ({ posts }: Props) => {
  // console.log(posts);
  return (
    <Layout>
      <div className="min-w-2xl max-w-7xl mx-auto">
        <Head>
          <title>Mediumize</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <AfterHeader />

          {/* Posts */}
          {posts.map((post) => (
            <Link key={post.slug} href={`${post.img as any as string}`}>
              <img
                src={
                  post.img
                    ? post.img
                    : "https://media.istockphoto.com/vectors/no-image-available-sign-vector-id922962354?k=20&m=922962354&s=612x612&w=0&h=f-9tPXlFXtz9vg_-WonCXKCdBuPUevOBkp3DQ-i0xqo="
                }
                width={300}
                height={300}
              />
            </Link>
          ))}
        </main>
      </div>
    </Layout>
  );
};

export const getServerSideProps = async () => {
  const res = await fetch(`http://127.0.0.1:8000/posts/`);
  const posts = await res.json();
  console.log(posts);

  if (!posts) {
    return {
      notFound: true,
    };
  }
  return { props: { posts } };
};

export default Home;
