import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import AfterHeader from "../components/AfterHeader";
import Layout from "../components/Layout";

const Home: NextPage = () => {
    return (
        <Layout>
            <div className="min-w-2xl max-w-7xl mx-auto">
                <Head>
                    <title>Mediumize</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <main>
                    <AfterHeader />
                </main>
            </div>
        </Layout>
    );
};

export default Home;
