import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
    return (
        <div className="first-letter:">
            <Head>
                <title>Mediumize</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>This is where the content goes</main>
        </div>
    )
}

export default Home
