# Generated by Django 4.0.2 on 2022-03-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
